package clashsoft.mods.moretools;

import cpw.mods.fml.common.ModMetadata;

import net.minecraft.entity.player.EntityPlayer;

import clashsoft.cslib.minecraft.update.CSUpdate;
import clashsoft.cslib.util.CSArrays;

public class MTMVersion
{
	public static final String		MODID			= "moretools";
	public static final String		NAME			= "More Tools Mod";
	public static final String		ACRONYM			= "mtm";
	
	public static final int			REVISION		= 0;
	public static final String		VERSION			= CSUpdate.CURRENT_VERSION + "-" + REVISION;
	
	public static void write(ModMetadata metadata)
	{
		metadata.autogenerated = false;
		metadata.name = NAME;
		metadata.modId = MODID;
		metadata.version = VERSION;
		metadata.logoFile = "moretools:logo.png";
		metadata.url = "https://github.com/Clashsoft/More-Tools-Mod/wiki";
		metadata.authorList = CSArrays.asList("Clashsoft");
	}
	
	public static void updateCheck(EntityPlayer player)
	{
		CSUpdate.csUpdateCheck(player, NAME, ACRONYM, VERSION);
	}
}
